// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using YouDefine.Data;

namespace YouDefine.Migrations
{
    [DbContext(typeof(YouDefineContext))]
    partial class YouDefineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YouDefine.Data.Definition", b =>
                {
                    b.Property<long>("DefinitionId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<long>("IdeaId");

                    b.Property<int>("Likes");

                    b.Property<string>("Text");

                    b.HasKey("DefinitionId");

                    b.HasIndex("IdeaId");

                    b.ToTable("Definitions");
                });

            modelBuilder.Entity("YouDefine.Data.Idea", b =>
                {
                    b.Property<long>("IdeaId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<int>("Likes");

                    b.Property<string>("Title");

                    b.HasKey("IdeaId");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("YouDefine.Data.Definition", b =>
                {
                    b.HasOne("YouDefine.Data.Idea")
                        .WithMany("Definitions")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
